### ISSUE TITLE
Closing span tag written to wrong location

### ISSUE THREAD

**Issue by kevin-bkt** [antiufo/Shaman.Dom#2]
Using version 1.0.1.16 of Shaman.Dom, there is incorrect output when serializing the attached html file "test.html".  Create an HtmlDocument instance from this file, then write the HtmlDocument to a new file using the WriteTo() method.  You will find that a `<span/>` closing tag has been added on line 116.  This has the effect of placing the two `<div>` tags on lines 114 and 115 before the `<span/>` when they should be after the `<span/>`.  View the output file "test.out.html" to see this.

[TestHtml.zip](https://github.com/antiufo/Shaman.Dom/files/653287/TestHtml.zip)

**Comment by antiufo** [comment]
In HTML5, as opposed to XML, self-closing tags don't work the way you would expect.
http://stackoverflow.com/questions/3558119/are-self-closing-tags-valid-in-html5/3558200#3558200

`<div/><span/>` is parsed both by browsers and by Shaman.Dom as `<div><span></span></div>`, because end slashes for non-void elements are required to be ignored.
However, the error recovery strategy ends up working differently in browsers and in `Shaman.Dom`, this is why the DOM tree is reconstructed in slightly different ways.

**Comment by kevin-bkt** [comment]
Thank you for the explanation.  In this case, the browser (Firefox or Chrome) renders this properly.  After processing through Shaman.Dom, it does not render properly.  This says to me that Shaman.Dom needs to have a strategy for interpreting HTML that can accommodate these differences.  Otherwise, it leaves it to the developer to wrap Shaman.Dom in code that will do so.

**Comment by antiufo** [comment]
Shaman.Dom is a fork of HtmlAgilityPack. It's wasn't meant to be a 100% compliant HTML5 parser.
